export const tokens = {
  font: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
    mono: 'var(--font-mono)',
  },
  text: {
    xs: 'var(--text-xs)',
    sm: 'var(--text-sm)',
    base: 'var(--text-base)',
    lg: 'var(--text-lg)',
    xl: 'var(--text-xl)',
    '2xl': 'var(--text-2xl)',
    '3xl': 'var(--text-3xl)',
    '4xl': 'var(--text-4xl)',
    '5xl': 'var(--text-5xl)',
  },
  weight: {
    regular: 'var(--font-weight-regular)',
    medium: 'var(--font-weight-medium)',
    semibold: 'var(--font-weight-semibold)',
    bold: 'var(--font-weight-bold)',
  },
  leading: {
    tight: 'var(--leading-tight)',
    snug: 'var(--leading-snug)',
    normal: 'var(--leading-normal)',
    relaxed: 'var(--leading-relaxed)',
  },
  tracking: {
    tight: 'var(--tracking-tight)',
    normal: 'var(--tracking-normal)',
    wide: 'var(--tracking-wide)',
  },
  color: {
    brandPrimary: 'var(--color-brand-primary)',
    brandSecondary: 'var(--color-brand-secondary)',
    accentWarm: 'var(--color-accent-warm)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    danger: 'var(--color-danger)',
    info: 'var(--color-info)',
    bgBase: 'var(--color-bg-base)',
    bgSurface: 'var(--color-bg-surface)',
    bgMuted: 'var(--color-bg-muted)',
    surfaceBase: 'var(--color-surface-base)',
    surfaceRaised: 'var(--color-surface-raised)',
    surfaceSunken: 'var(--color-surface-sunken)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    textInverse: 'var(--color-text-inverse)',
    borderSubtle: 'var(--color-border-subtle)',
    borderStrong: 'var(--color-border-strong)',
    borderFocus: 'var(--color-border-focus)',
    stateHoverOverlay: 'var(--color-state-hover-overlay)',
    stateActiveOverlay: 'var(--color-state-active-overlay)',
    stateSelectedBg: 'var(--color-state-selected-bg)',
    bgLavender: 'var(--color-bg-lavender)',
    bgMint: 'var(--color-bg-mint)',
    bgPeach: 'var(--color-bg-peach)',
    bgSlate: 'var(--color-bg-slate)',
    bgRose: 'var(--color-bg-rose)',
  },
  gradient: {
    p: 'var(--gradient-p)',
    warm: 'var(--gradient-warm)',
    cool: 'var(--gradient-cool)',
    fresh: 'var(--gradient-fresh)',
    sunset: 'var(--gradient-sunset)',
    iridescent: 'var(--gradient-iridescent)',
    shimmer: 'var(--gradient-shimmer)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    pill: 'var(--radius-pill)',
  },
  shadow: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    glowPrimary: 'var(--shadow-glow-primary)',
    glowWarm: 'var(--shadow-glow-warm)',
    glowCool: 'var(--shadow-glow-cool)',
  },
  spacing: {
    sidebarCollapsed: 'var(--spacing-sidebar-collapsed)',
    sidebarExpanded: 'var(--spacing-sidebar-expanded)',
    header: 'var(--spacing-header)',
    copilotCollapsed: 'var(--spacing-copilot-collapsed)',
    copilotExpanded: 'var(--spacing-copilot-expanded)',
    contentMax: 'var(--content-max)',
  },
  duration: {
    fast: 'var(--duration-fast)',
    base: 'var(--duration-base)',
    slow: 'var(--duration-slow)',
    slower: 'var(--duration-slower)',
  },
  easing: {
    dopamine: 'var(--ease-dopamine)',
    standard: 'var(--ease-standard)',
  },
  motion: {
    enter: 'var(--motion-enter)',
    exit: 'var(--motion-exit)',
    bounce: 'var(--motion-bounce)',
  },
} as const;

export type Tokens = typeof tokens;
